### ISSUE TITLE
Activer le menu "What we do ?"

### ISSUE THREAD

**Issue by ouadie-lahdioui** [ngMorocco/ngMorocco-profile#2]
Yo,

J'ai commencé le travail sur la page "What we do ?" mais je nais pas pu la finaliser.

Je remonte ce ticket pour ne pas oublier de travailler là-dessus 👍 

Ma source d'inspiration :  
- Le bloque "About AngularCamp" de nos amis http://angularcamp.org

Je trouve également que la bannière en bas peut être utile !

<img width="1393" alt="capture d ecran 2016-07-05 a 12 36 32" src="https://cloud.githubusercontent.com/assets/2996203/16584588/660bbb56-42ac-11e6-8dde-4bf2d65035ee.png">

**Comment by intissarMez** [comment]
Salut !

Je m'en occupe Tkt ...
